#!/usr/bin/env bash
set -euo pipefail

usage() {
  echo "Usage: $0 <workspace-root-path>"
}

WORKSPACE_ROOT="${1:-}"
if [[ -z "$WORKSPACE_ROOT" ]]; then
  usage
  exit 2
fi

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
CONTROL_PLANE_ROOT="$(cd "$SCRIPT_DIR/../.." && pwd)"

if git -C "$CONTROL_PLANE_ROOT" remote get-url origin >/dev/null 2>&1; then
  echo "INFO: pulling latest control plane from main"
  git -C "$CONTROL_PLANE_ROOT" pull --ff-only origin main || {
    echo "WARN: pull failed, continuing with local control plane state"
  }
else
  echo "INFO: no origin remote configured, using local control plane state"
fi

mkdir -p "$WORKSPACE_ROOT"

DATE_UTC="$(date -u +%F)"

cat > "$WORKSPACE_ROOT/AGENTS.md" <<EOF
# AUTO-GENERATED by sync-workspace.sh from Level-0 templates. Do not edit manually.

# Workspace AGENTS

Generated on: $DATE_UTC
Control plane: $CONTROL_PLANE_ROOT (main)

This workspace-level file is a runtime materialization layer.
Canonical governance lives in the Level-0 control plane repository.
EOF

cat > "$WORKSPACE_ROOT/CLAUDE.md" <<EOF
# AUTO-GENERATED by sync-workspace.sh from Level-0 templates. Do not edit manually.

# Workspace CLAUDE

Generated on: $DATE_UTC
Control plane: $CONTROL_PLANE_ROOT (main)

This is a workspace runtime file. Update Level-0 templates and re-run sync.
EOF

echo "OK: generated $WORKSPACE_ROOT/AGENTS.md"
echo "OK: generated $WORKSPACE_ROOT/CLAUDE.md"
